name: NodeJS Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 18 ]

    env:
      Archive_Name: '../SwitchSetup_Preview.zip'

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build-win

    - name: Add manifest
      run: node manifest.js

    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: "zip"
        path: "./bin/*"
        filename: ${{ env.Archive_Name }}

    - name: Generate Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: ${{ env.Archive_Name }}
