name: NodeJS Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 18 ]

    env:
      Archive_Name: '../SwitchSetup_Preview.zip'

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build-win

    - name: Add manifest
      run: node manifest.js
      
    - name: Sign Binaries
      uses: GabrielAcostaEngler/signtool-code-sign@main
      with:
        certificate: '${{ secrets.Base64_Encoded_PFX }}'
        cert-password: '${{ secrets.PFX_KEY }}'
        cert-sha1: '${{ secrets.PFX_SHA1 }}'
        cert-description: 'foo'
        folder: '../_build'
        recursive: false
        timestamp-server: 'http://timestamp.digicert.com'

    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: "zip"
        path: "./bin/*"
        filename: ${{ env.Archive_Name }}
        
    - name: Generate Release
      uses: "Shinerising/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: ${{ env.Archive_Name }}
